- hosts: masters
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "{{ es_master_heap_size }}"
    es_data_dirs:
      - "{{ es_data_dir | join('') }}/elasticsearch"
    es_config:
      cluster.name: "{{ es_cluster_name }}"
      network.host: 0
      cluster.initial_master_nodes: "{{ groups['masters'] | list  }}"
      discovery.seed_hosts: "{{ groups['masters'][0] }}"
      http.port: 9200
      node.data: true
      node.master: true
      node.ingest: true
      node.ml: true
      cluster.remote.connect: false
      bootstrap.memory_lock: true
      xpack.security.enabled: false
      xpack.monitoring.enabled: true

      searchguard.enterprise_modules_enabled: false

      searchguard.ssl.transport.pemcert_filepath: "{{ sg_transport_pemfile }}"
      searchguard.ssl.transport.pemkey_filepath: "{{ sg_transport_keyfile }}"
      searchguard.ssl.transport.pemkey_password: "{{ sg_transport_keypass }}"
      searchguard.ssl.transport.pemtrustedcas_filepath: "{{ sg_trusted_cas_transport }}"
      searchguard.ssl.transport.enforce_hostname_verification: "{{ sg_ssl_ver }}"
      searchguard.ssl.transport.resolve_hostname: "{{ sg_ssl_ver }}"
      searchguard.ssl.http.enabled: "{{ sg_http_enabled }}"
      searchguard.ssl.http.pemcert_filepath: "{{ sg_http_pemfile }}"
      searchguard.ssl.http.pemkey_filepath: "{{ sg_http_keyfile }}"
      searchguard.ssl.http.pemkey_password: "{{ sg_http_keypass }}"
      searchguard.ssl.http.pemtrustedcas_filepath: "{{ sg_trusted_cas_http }}"
      searchguard.authcz.admin_dn:
      - "{{ sg_admin_dn }}"
      searchguard.cert.oid: 1.2.3.4.5.5

      searchguard.enable_snapshot_restore_privilege: true
      searchguard.check_snapshot_restore_write_privileges: true
      searchguard.restapi.roles_enabled: ["SGS_ALL_ACCESS"]
      searchguard.nodes_dn:
      - "CN=instance.example.in,OU=Ops,O=example\\, tech pvt. ltd.,DC=example,DC=in"

    es_plugins:
      - plugin: "file:///home/ec2-user/search-guard-suite-plugin-7.10.1-48.0.0.zip"
- hosts: data
  roles:
    - role: elastic.elasticsearch
  vars:
    es_data_dirs:
      - "{{ es_data_dir | join('') }}/elasticsearch"
    es_heap_size: "{{ es_data_heap_size }}"
    es_config:
      cluster.name: "{{ es_cluster_name }}"
      network.host: 0
      discovery.seed_hosts: "{{ groups['masters'][0] }}"
      http.port: 9200
      node.data: true
      node.master: false
      node.ml: false
      bootstrap.memory_lock: true
      indices.recovery.max_bytes_per_sec: 100mb
      searchguard.enterprise_modules_enabled: false
      xpack.security.enabled: false
      xpack.monitoring.enabled: true

      searchguard.ssl.transport.pemcert_filepath: "{{ sg_transport_pemfile }}"
      searchguard.ssl.transport.pemkey_filepath: "{{ sg_transport_keyfile }}"
      searchguard.ssl.transport.pemkey_password: "{{ sg_transport_keypass }}"
      searchguard.ssl.transport.pemtrustedcas_filepath: "{{ sg_trusted_cas_transport }}"
      searchguard.ssl.transport.enforce_hostname_verification: "{{ sg_ssl_ver }}"
      searchguard.ssl.transport.resolve_hostname: "{{ sg_ssl_ver }}"
      searchguard.ssl.http.enabled: "{{ sg_http_enabled }}"
      searchguard.ssl.http.pemcert_filepath: "{{ sg_http_pemfile }}"
      searchguard.ssl.http.pemkey_filepath: "{{ sg_http_keyfile }}"
      searchguard.ssl.http.pemkey_password: "{{ sg_http_keypass }}"
      searchguard.ssl.http.pemtrustedcas_filepath: "{{ sg_trusted_cas_http }}"
      searchguard.authcz.admin_dn:
      - "{{ sg_admin_dn }}"
      searchguard.cert.oid: 1.2.3.4.5.5

      searchguard.enable_snapshot_restore_privilege: true
      searchguard.check_snapshot_restore_write_privileges: true
      searchguard.restapi.roles_enabled: ["sg_all_access"]
      searchguard.nodes_dn:
      - "CN=instance.example.in,OU=Ops,O=example\\, tech pvt. ltd.,DC=example,DC=in"

    es_plugins:
      - plugin: "file:///home/ec2-user/search-guard-suite-plugin-7.10.1-48.0.0.zip"
- hosts: coordinating
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "{{ es_coord_heap_size }}"
    es_data_dirs:
      - "{{ es_data_dir | join('') }}/elasticsearch"
    es_config:
      cluster.name: "{{ es_cluster_name }}"
      network.host: 0
      discovery.seed_hosts: "{{ groups['masters'][0] }}"
      http.port: 9200
      node.data: false
      node.master: false
      node.ingest: false
      node.ml: false
      bootstrap.memory_lock: true
      searchguard.enterprise_modules_enabled: false
      xpack.security.enabled: false
      xpack.monitoring.enabled: true

      searchguard.ssl.transport.pemcert_filepath: "{{ sg_transport_pemfile }}"
      searchguard.ssl.transport.pemkey_filepath: "{{ sg_transport_keyfile }}"
      searchguard.ssl.transport.pemkey_password: "{{ sg_transport_keypass }}"
      searchguard.ssl.transport.pemtrustedcas_filepath: "{{ sg_trusted_cas_transport }}"
      searchguard.ssl.transport.enforce_hostname_verification: "{{ sg_ssl_ver }}"
      searchguard.ssl.transport.resolve_hostname: "{{ sg_ssl_ver }}"
      searchguard.ssl.http.enabled: "{{ sg_http_enabled }}"
      searchguard.ssl.http.pemcert_filepath: "{{ sg_http_pemfile }}"
      searchguard.ssl.http.pemkey_filepath: "{{ sg_http_keyfile }}"
      searchguard.ssl.http.pemkey_password: "{{ sg_http_keypass }}"
      searchguard.ssl.http.pemtrustedcas_filepath: "{{ sg_trusted_cas_http }}"
      searchguard.authcz.admin_dn:
      - "{{ sg_admin_dn }}"
      searchguard.cert.oid: 1.2.3.4.5.5

      searchguard.enable_snapshot_restore_privilege: true
      searchguard.check_snapshot_restore_write_privileges: true
      searchguard.restapi.roles_enabled: ["sg_all_access"]
      searchguard.nodes_dn:
      - "CN=instance.example.in,OU=Ops,O=example\\, tech pvt. ltd.,DC=example,DC=in"

    es_plugins:
      - plugin: "file:///home/ec2-user/search-guard-suite-plugin-7.10.1-48.0.0.zip"
